name: masar_jobs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0

  # UI & Animation
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  rive: ^0.13.4
  custom_refresh_indicator: ^3.0.0


  # Functionality
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  video_player: ^2.8.6
  file_picker: ^8.0.5   # لاختيار أي نوع من الملفات (مثل PDF)
  sensors_plus: ^5.0.1  # للاستجابة لحركة الهاتف
  just_audio: ^0.9.36
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  image: ^4.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/rive/
    - assets/image/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700